#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $SECURITY_DB_USER WITH PASSWORD '$SECURITY_DB_PASS';
    CREATE DATABASE $SECURITY_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $SECURITY_DB_NAME TO $SECURITY_DB_NAME;
EOSQL
