_format_version: "1.1"

services:
  - name: adoption
    url: http://adoption-web
    tags:
      - microservice
    routes:
      - name: adoption-offers
        strip_path: false
        paths:
          - /offers(.*)
      - name: adoption-register-shelter
        strip_path: false
        paths:
          - /shelters
      - name: adoption-register-adopter
        strip_path: false
        paths:
          - /adopters
  - name: security
    url: http://security-web
    routes:
      - name: login
        strip_path: false
        paths:
          - /login

plugins:
  - name: correlation-id
    config:
      header_name: Correlation-Id
  - name: tcp-log
    config:
      host: elk
      port: 5400
